version: '3.8'
services:
  bookmarker-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=appdb
    ports:
      - "15432:5432"










